language: cpp
os:
- windows
notifications:
  webhooks:
    urls:
      secure: https://discordapp.com/api/webhooks/237606690495791104/ewURTxkzbXphiOgXbzImxaHAsFCDuIDsVIDSADAeSs8a_6sd5VgWGWUG42Ij_qRTkocf
    on_success: always
    on_failure: always
    on_start: always
