version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
build:
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/237606690495791104/ewURTxkzbXphiOgXbzImxaHAsFCDuIDsVIDSADAeSs8a_6sd5VgWGWUG42Ij_qRTkocf
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
